# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en 
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://alyonavyshnevska.github.io
baseurl: 
title: Alyona Vyshnevska
description: "hi"
keywords: alyona vyshnevska, alyona, vyshnevska, cognitive systems
author:
  name: Alyona Vyshnevska
  job_title:
  location:
  email: vyshnevska@uni-potsdam.de
  social_links:
    - name: 500px
      url: https://500px.com/alyona_
    - name: github
      url: https://github.com/alyonavyshnevska

home:
  section1: <h1>Hi, my name is Alyona. </h1>
  section2: <h2 class="aboutme"> I am a Cognitive Systems student at the University of Potsdam. <br>These days I do things with natural language processing, <br> machine learning, and text visualisation. </h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/alyonavyshnevska" title="GitHub"></a></div>


paths:
  home: /
